version: "3"

services:
  client:
    container_name: client
    image: node:16.15.1
    volumes:
      - ./client:/app
    env_file:
      - ./client/.env
    ports:
      - "8000:8000"
    command: sh -c "cd /app && yarn && yarn start"
  server:
    container_name: server
    image: node:16.15.1
    depends_on:
      - db
    ports:
      - "3000:3000"
    volumes:
      - ./server:/app
    command: sh -c "cd /app && yarn && yarn start:dev"
  db:
    container_name: db
    image: mariadb:10.5.8
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: remitano
    volumes:
      - ./database/data:/var/lib/mysql
